# Generated by Django 4.1.7 on 2023-03-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0033_orders_completed_alter_orders_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newproducts/'),
        ),
    ]
